# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_choice(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 201)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-360, -110, 771, 511))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1653656807_23-celes-club-p-fon-raznotsvetnie-klyaksi-krasivie-24.jpg"))
        self.label.setObjectName("label")
        self.spinBox_choice = QtWidgets.QSpinBox(Form)
        self.spinBox_choice.setGeometry(QtCore.QRect(130, 90, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_choice.setFont(font)
        self.spinBox_choice.setObjectName("spinBox_choice")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(170, 170, 255, 180);\n"
"color: rgb(41, 0, 61);")
        self.label_2.setObjectName("label_2")
        self.pushButton_choice = QtWidgets.QPushButton(Form)
        self.pushButton_choice.setGeometry(QtCore.QRect(290, 160, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(14)
        self.pushButton_choice.setFont(font)
        self.pushButton_choice.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_choice.setObjectName("pushButton_choice")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Выбор работы для просмотра"))
        self.pushButton_choice.setText(_translate("Form", "Выбрать"))
