# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_in(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 324)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-330, -50, 831, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1653656807_23-celes-club-p-fon-raznotsvetnie-klyaksi-krasivie-24.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(50, 0, 75);")
        self.label_2.setObjectName("label_2")
        self.pushButton_avtor = QtWidgets.QPushButton(Form)
        self.pushButton_avtor.setGeometry(QtCore.QRect(100, 110, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_avtor.setFont(font)
        self.pushButton_avtor.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_avtor.setObjectName("pushButton_avtor")
        self.pushButton_learning = QtWidgets.QPushButton(Form)
        self.pushButton_learning.setGeometry(QtCore.QRect(100, 190, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_learning.setFont(font)
        self.pushButton_learning.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_learning.setObjectName("pushButton_learning")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 60, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(50, 0, 75);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Добро пожаловать"))
        self.pushButton_avtor.setText(_translate("Form", "Авторизоваться"))
        self.pushButton_learning.setText(_translate("Form", "Изучить курсы"))
        self.label_3.setText(_translate("Form", "в онлайн-школу рисования!"))
