# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_logg(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(445, 250)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-270, -150, 721, 491))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1653656807_23-celes-club-p-fon-raznotsvetnie-klyaksi-krasivie-24.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(225, 225, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(225, 225, 255);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_log = QtWidgets.QLineEdit(Form)
        self.lineEdit_log.setGeometry(QtCore.QRect(160, 70, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_log.setFont(font)
        self.lineEdit_log.setObjectName("lineEdit_log")
        self.lineEdit_pas = QtWidgets.QLineEdit(Form)
        self.lineEdit_pas.setGeometry(QtCore.QRect(160, 140, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_pas.setFont(font)
        self.lineEdit_pas.setObjectName("lineEdit_pas")
        self.pushButton_inp = QtWidgets.QPushButton(Form)
        self.pushButton_inp.setGeometry(QtCore.QRect(320, 210, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_inp.setFont(font)
        self.pushButton_inp.setStyleSheet("color: rgb(39, 0, 58);\n"
"background-color: rgb(170, 170, 255);")
        self.pushButton_inp.setObjectName("pushButton_inp")
        self.pushButton_back = QtWidgets.QPushButton(Form)
        self.pushButton_back.setGeometry(QtCore.QRect(320, 20, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setStyleSheet("color: rgb(39, 0, 58);\n"
"background-color: rgb(170, 170, 255);")
        self.pushButton_back.setObjectName("pushButton_back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Login:"))
        self.label_3.setText(_translate("Form", "Password:"))
        self.pushButton_inp.setText(_translate("Form", "Войти"))
        self.pushButton_back.setText(_translate("Form", "Назад"))
