# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_view(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 528)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-190, -10, 911, 701))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1653656807_23-celes-club-p-fon-raznotsvetnie-klyaksi-krasivie-24.jpg"))
        self.label.setObjectName("label")
        self.label_photo = QtWidgets.QLabel(Form)
        self.label_photo.setGeometry(QtCore.QRect(40, 30, 581, 411))
        self.label_photo.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.label_photo.setText("")
        self.label_photo.setObjectName("label_photo")
        self.pushButton_close = QtWidgets.QPushButton(Form)
        self.pushButton_close.setGeometry(QtCore.QRect(510, 470, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_close.setObjectName("pushButton_close")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_close.setText(_translate("Form", "Закрыть"))
